version: "2"
checks:
  argument-count:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  return-statements:
    config:
      threshold: 8
plugins:
  fixme:
    enabled: true
  pmd:
    enabled: true
  sonar-java:
    enabled: true
    config:
      sonar.java.source: 17
  duplication:
    enabled: true
    config:
      languages:
        java:
          mass_threshold: 60
ratings:
  paths:
  - "**.java"
exclude_patterns: []
