language: java
jdk: oraclejdk7

before_install:
  - chmod +x gradlew

script: ./gradlew build

after_success:
  - ls ./build/libs

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file_glob: true
    file: ./build/libs/CheesecakeServerCommands*.jar
    skip_cleanup: true
    on:
        tags: true