language: java
jdk: oraclejdk7

before_install:
  - chmod +x gradlew

script: ./gradlew build

after_success:
  - ls ./build/libs

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file_glob: true
    file: ./build/libs/CheesecakeServerCommands*.jar
    skip_cleanup: true
    on:
        tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#itachi1706mc"
      - "irc.esper.net#itachi1706"
    on_success: always
    on_failure: always
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{commit_subject}"
      - "Build Status : %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
  email:
    recipients:
      - $PRIVATE_EMAIL
    on_success: change # default: change
    on_failure: always # default: always